stages:
  - check

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


nix_check:
  stage: check
  needs: []
  tags:
    - nix
  script:
    - nix --extra-experimental-features "nix-command flakes" flake check
