keys:
  - &kloenk_age age1p06k9fwwdhwcx6qxt5fyypkdk9wpkhk5fhyzjnykaymz32nwsakqwyfjqm
  - &kloenk_gpg B44ADFDFF869A66A3FDFDD8B8609A7B519E5E342
  - &server_thrain age1ejyvncc2g7slp30fx72cyawg5z5030mzfq6zy8fk3tm2n72pqghsfmrvp6
  - &server_elros age1qcf0vrljqh34skeqpx4jh4x4e9400acn3rf5tqdy2697603ncfyqasa5df
  - &server_gimli age1we86kfnan67mq7eks89ndz85w299j35un400jvlrhk3ktjyhkgks69lz62
  - &server_varda age1vfrdpq9p6qm8yf4ddrzhy6mutzrzgauv6vp9gjq99t5kmcd8lp4sf9gyum
  - &server_vaire age13kssfhekukyqay3rzv4ssdaj40hu4zhal9e2vrxemfkyu37pjfts37hsme
  - &server_sc-social age1np3d3s6nj80l7dvakj7welwyl26upgmwv8ykvv23q452fm6kk9fqcfk880
  - &server_moodle age1xq2s075hy7fah8la38jpa642f2j4zvhv7qa3c4gprhcyhkx8rsastndc4q
  - &server_elrond age1tvgutz4vzmqf3xqnckt9karpd467nj6vft80al8nfvpu02ck43sqneqwht
  - &server_gloin age157nvp7sxxl5zsp6pyn5ng8fy5up9ghmwtf02wtz5rk5wc836v4zq2ha4fs
  - &server_ktest age14xp569xqe7xjkhrkz4gg5gz6fc45frmml3z43an2378dc4735u3shyk7n9
  - &server_strider age1uc3uylajglal6ql32r8yjpwhu7zlhep04ka7udds405c92eg3fssadyyuk
  - &server_fingolfin age1s920f262j8tmky0r2vgc2w2mnxyn2mla7vtjhu7nnk3q2w8tvysq9wxu0q
  - &darwin_frodo age1k2uq8d4pal0mlh4c0vc694p0esz8q2q6tnxgzjrguv3gh2ca9s3qukgl62
creation_rules:
  - path_regex: secrets/thrain[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_thrain
  - path_regex: secrets/elros[^/]*\.yaml$
    key_groups:
    - age:
        - *kloenk_age
        - *server_elros
      pgp:
        - *kloenk_gpg
  - path_regex: secrets/gimli[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_gimli
  - path_regex: secrets/varda[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_varda
  - path_regex: secrets/vaire[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_vaire
  - path_regex: secrets/sc-social[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_sc-social
  - path_regex: secrets/moodle-usee[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_moodle
  - path_regex: secrets/elrond[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_elrond
  - path_regex: secrets/gloin[^/]*\.yaml$
    shamir_threshold: 1
    key_groups:
    - age:
        - *kloenk_age
        - *server_gloin
      pgp:
        - *kloenk_gpg
  - path_regex: secrets/fingolfin[^/]*\.yaml$
    shamir_threshold: 1
    key_groups:
    - age:
        - *kloenk_age
        - *server_fingolfin
      pgp:
        - *kloenk_gpg	
  - path_regex: secrets/shared/[^/]*\.yaml$
    key_groups:
    - age:
        - *kloenk_age
        - *server_thrain
        - *server_elros
        - *server_gimli
        - *server_varda
        - *server_vaire
        - *server_moodle
        - *server_elrond
        - *server_gloin
        - *darwin_frodo
        - *server_sc-social
        - *server_ktest
        - *server_strider
        - *server_fingolfin
      pgp:
        - *kloenk_gpg
  - path_regex: secrets/.+\.yaml$
    key_groups:
    - age:
      - *kloenk_age

