keys:
  - &kloenk_age age1p06k9fwwdhwcx6qxt5fyypkdk9wpkhk5fhyzjnykaymz32nwsakqwyfjqm

  - &server_thrain age1ejyvncc2g7slp30fx72cyawg5z5030mzfq6zy8fk3tm2n72pqghsfmrvp6
  - &server_manwe age1q0kl8evx9pqtnvwu5ae43d5m9v33kv52xmd7t3e5zrxqzqw7tdeq2c6z5m
  - &server_gimli age1we86kfnan67mq7eks89ndz85w299j35un400jvlrhk3ktjyhkgks69lz62
  - &server_iluvatar age19fmyhd7h722ag68g72pv72w4g44fqzs6qpl5ra0e4mtxa204e3vsp8eq6h
  - &server_moodle age1xq2s075hy7fah8la38jpa642f2j4zvhv7qa3c4gprhcyhkx8rsastndc4q
  - &server_samwise age1e7sgfwlfzq3vud6xdg32wqvdugk80lpcd6nu3v755t04qpewxf5qnpj752
  - &server_durin age1rv84hd56gxt4gcum99ne9q4cxxzx32h8gu4dh4mzu6pf3shujfnqhfx6pe
  - &server_elrond age1tvgutz4vzmqf3xqnckt9karpd467nj6vft80al8nfvpu02ck43sqneqwht
  - &darwin_frodo age1wwptqz272d4la84kvshrw3ds2mpqffhyjhr2zm747sfc4ztdefkq6fspyz
creation_rules:
  - path_regex: secrets/thrain[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *server_thrain
  - path_regex: secrets/manwe[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_manwe
  - path_regex: secrets/gimli[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_gimli
  - path_regex: secrets/iluvatar[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_iluvatar
  - path_regex: secrets/moodle-usee[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_moodle
  - path_regex: secrets/samwisethink[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_samwise
  - path_regex: secrets/durin[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_durin
  - path_regex: secrets/shared/[^/]*\.yaml$
    key_groups:
      - age:
          - *kloenk_age
          - *server_thrain
          - *server_manwe
          - *server_gimli
          - *server_iluvatar
          - *server_moodle
          - *server_durin
          - *server_elrond
          - *darwin_frodo
  - path_regex: secrets/.+\.yaml$
    key_groups:
    - age:
      - *kloenk_age

