# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ec1008b1-23d9-46bd-97c4-5fc15bd6cce7";
      fsType = "xfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1b4761f3-bbc8-4e00-a9cb-80148d436620";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4C14-192A";
      fsType = "vfat";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/88ac85c5-258f-476f-9115-7a5be31f9e57";
      fsType = "xfs";
    };

  fileSystems."/root/.gnupg" =
    { device = "/persist/data/gnupg-root";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
}
