{
 "title": "BigBlueButton Server Instance",
 "tags": [
  "BigBlueButton",
  "prometheus",
  "netdata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Type of Users Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "bbb_meetings_listeners{instance=\"$instance\"}",
     "legendFormat": "Listeners"
    },
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice"
    },
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "CPU Utilization vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[2m])",
     "legendFormat": "{{job}} core{{cpu}}"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "Max Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Selected timeframe"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[1w])",
     "legendFormat": "Since 1 week"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_recordings_processing{instance=\"$instance\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "bbb_recordings_processed{instance=\"$instance\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "bbb_recordings_published{instance=\"$instance\"}",
     "legendFormat": "Published"
    },
    {
     "expr": "bbb_recordings_unpublished{instance=\"$instance\"}",
     "legendFormat": "Unpublished"
    },
    {
     "expr": "bbb_recordings_deleted{instance=\"$instance\"}",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Bandwidth vs. Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "Kbits", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{instance=~\"$instance\",device!=\"lo\"}[2m])) by (job)",
     "legendFormat": "{{job}} rx"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!=\"lo\"}[2m])) by (job)",
     "legendFormat": "{{job}} tx"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API 95-th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Latency [s]" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processing\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processed\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=published\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=unpublished\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=deleted\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings deleted"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "buffer"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "cached"
    }
   ]
  }
 ]
}