# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4522bfda-2863-4651-a393-da8472d64f5d";
      fsType = "xfs";
    };

  fileSystems."/boot/a" =
    { device = "/dev/disk/by-uuid/3c1bb778-e836-4ed6-b184-6f4c6b4a0760";
      fsType = "ext2";
    };

  fileSystems."/boot/b" =
    { device = "/dev/disk/by-uuid/cd7d0474-b2f4-4e23-beeb-2e2f078633ee";
      fsType = "ext2";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5cdb6bab-fda3-490e-acb1-3b1aac85523e";
      fsType = "xfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/07669d95-74a8-4b47-9962-10fecb135c5c";
      fsType = "xfs";
    };

  swapDevices = [ ];

}
