# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b4b95944-d3a1-49de-9c53-71c0781beec5";
      fsType = "xfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/b4e6550a-f105-41ac-8e60-f7856e62d174";
      fsType = "xfs";
    };

  fileSystems."/persist/data/fedora-32" =
    { device = "/dev/disk/by-uuid/663d4924-b5e0-43dd-a6bc-e19b61e853f8";
      fsType = "xfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/bd8b2c32-505c-4db3-9982-7fe0a3e7f89f";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B485-99A0";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5c64004f-3d0b-4669-a0d0-21b3c814d33e"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
