# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "hpsa" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fb5c8622-770e-4c65-8bc3-41982f716b40";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/873c10c3-fae5-4fe0-9447-89e698b2ac49";
      fsType = "ext2";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/50e1035f-6416-4161-b474-f6f1ffee74ef";
      fsType = "xfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ceb6dee9-1a68-4962-bca6-8878051bac1c";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b1bebbca-702e-4959-bf32-0c15c28c2ec4"; }
    ];

}
