{
 "title": "SSL Monitoring (x509_cert)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(x509_cert_expiry,host)"
    }
   },
   {
    "name": "ssl_name",
    "label": "SSL Certificate",
    "query": {
     "query": "label_values(x509_cert_expiry{host=~\"$host\", organization!=\"Let's Encrypt\"},common_name)"
    }
   },
   {
    "name": "cert_category",
    "label": "Cert Category",
    "query": {
     "query": "label_values(x509_cert_expiry{host=~\"$host\", common_name=~\"$ssl_name\"},cert_category)"
    }
   },
   {
    "name": "cert_source",
    "label": "Source",
    "query": {
     "query": "label_values(x509_cert_expiry{host=~\"$host\", common_name=~\"$ssl_name\", cert_category=~\"$cert_category\"},cert_source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certs valid",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(x509_cert_expiry{common_name=~\"$ssl_name\", host=~\"$host\", cert_category=~\"$cert_category\", cert_source=~\"$cert_source\", organization!=\"Let's Encrypt\"} > 2419200)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certs expiring",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(x509_cert_expiry{common_name=~\"$ssl_name\", host=~\"$host\", cert_category=~\"$cert_category\", cert_source=~\"$cert_source\", organization!=\"Let's Encrypt\"} < 2419200 > 604800)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certs expired",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(x509_cert_expiry{common_name=~\"$ssl_name\", host=~\"$host\", cert_category=~\"$cert_category\", cert_source=~\"$cert_source\", organization!=\"Let's Encrypt\"} < 604800)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "x509_cert_expiry{common_name=~\"$ssl_name\", host=~\"$host\", cert_category=~\"$cert_category\", cert_source=~\"$cert_source\", organization!=\"Let's Encrypt\", type=\"leaf\"}"
    }
   ]
  }
 ]
}