# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "spool/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7977-CFB7";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "spool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "spool/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/persist/postgres" =
    { device = "spool/safe/postgresql";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "spool/local/log";
      fsType = "zfs";
    };

  fileSystems."/persist/matrix" =
    { device = "hpool/safe/matrix";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
